name: mmolb_playoff_status
description: A web application to display MLB playoff status.
version: 0.0.1
repository: https://github.com/Mixolyde/mmolb-playoff-status

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  web: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^5.0.0
